# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Classifier.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(710, 560)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(710, 560))
        MainWindow.setMaximumSize(QtCore.QSize(710, 560))
        MainWindow.setStyleSheet("color: rgb(0, 85, 127);\n"
"\n"
"background-color: rgb(247, 247, 247);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(38, 29, 381, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(32, 438, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit.setGeometry(QtCore.QRect(33, 482, 641, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LineEdit.setFont(font)
        self.LineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(68, 68, 68);")
        self.LineEdit.setReadOnly(True)
        self.LineEdit.setObjectName("LineEdit")

        # self.pushButton11 = QtWidgets.QPushButton(self.centralwidget)
        # self.pushButton11.setGeometry(QtCore.QRect(430, 70, 341, 23))
        # self.pushButton11.setObjectName("pushButton11")

        self.Button1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button1.setGeometry(QtCore.QRect(31, 366, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Button1.setFont(font)
        self.Button1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 127)")
        self.Button1.setObjectName("Button1")
        self.Button2 = QtWidgets.QPushButton(self.centralwidget)
        self.Button2.setGeometry(QtCore.QRect(373, 366, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Button2.setFont(font)
        self.Button2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 127)\n"
"")
        self.Button2.setObjectName("Button2")
        self.TextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.TextEdit.setGeometry(QtCore.QRect(32, 76, 641, 271))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TextEdit.setFont(font)
        self.TextEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(16, 16, 16);")
        self.TextEdit.setObjectName("TextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 710, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Классификатор текста"))
        self.label1.setText(_translate("MainWindow", "Введите текст:"))
        self.label2.setText(_translate("MainWindow", "Тематика данного текста:"))
        self.Button1.setText(_translate("MainWindow", "Определить тематику"))
        self.Button2.setText(_translate("MainWindow", "Очистить"))
